{% import 'macros.jinja' as macros with context %}
{{ macros.github_header() }}
jobs:
  build:
    name: "Build wheel for Windows ARM64"
    runs-on: "{{ runs_on }}"
    timeout-minutes: 90
    env:
      PYTHON_CMD: "py -{{ python_version }}"
      CMAKE_BUILD_TYPE: release
    steps:
      - name: Disable Crash Dialogs
        run: |
          reg add `
            "HKCU\SOFTWARE\Microsoft\Windows\Windows Error Reporting" `
            /v DontShowUI `
            /t REG_DWORD `
            /d 1 `
            /f
      
      {{ macros.github_checkout_arrow()|indent }}
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "{{ python_version }}"
          architecture: "ARM64"
      # ---------------- ccache setup ---------------- #
      - name: Install ccache
        shell: bash
        run: |
          arrow/ci/scripts/install_ccache.sh 4.12.1 /usr
      - name: Setup ccache
        shell: bash
        run: |
          arrow/ci/scripts/ccache_setup.sh
      - name: ccache info
        id: ccache-info
        shell: bash
        run: |
          echo "dir=$(ccache --get-config cache_dir)" >> $GITHUB_OUTPUT
      - name: Cache ccache
        uses: actions/cache@v4
        with:
          path: {% raw %}${{ steps.ccache-info.outputs.dir }}{% endraw %}
          key: {% raw %}cpp-ccache-windows-arm64-${{ hashFiles('cpp/**') }}{% endraw %}
          restore-keys: cpp-ccache-windows-arm64-
      # ------------------------------------------------ #
      - name: Cache vcpkg installed artifacts
        uses: actions/cache@v4
        with:
          path: C:\vcpkg\installed
          key: {% raw %}vcpkg-installed-windows-arm64-${{ hashFiles('arrow/ci/vcpkg/vcpkg.json', 'arrow/ci/vcpkg/arm64-windows-*.cmake') }}{% endraw %}
          restore-keys: vcpkg-installed-windows-arm64-
      - name: Copy vcpkg ARM64 triplet files
        shell: cmd
        run: |
          copy arrow\ci\vcpkg\arm64-windows-*.cmake C:\vcpkg\triplets\community\
      
      - name: Install vcpkg dependencies
        shell: cmd
        run: |
          cd arrow\ci\vcpkg
          C:\vcpkg\vcpkg.exe install ^
            --binarysource=clear ^
            --binarysource="x-gha,readwrite" ^
            --x-install-root=C:\vcpkg\installed ^
            --x-manifest-root=. ^
            --x-feature=flight ^
            --x-feature=json ^
            --x-feature=orc ^
            --x-feature=parquet ^
            --x-feature=s3
      - name: Build Arrow C++ and PyArrow wheel
        shell: cmd
        env:
          SETUPTOOLS_SCM_PRETEND_VERSION: "{{ arrow.no_rc_version }}"
        run: |
          call "arrow\ci\scripts\python_wheel_windows_build_arm64.bat"
      - name: ccache stats
        if: always()
        shell: bash
        run: ccache -s
      - uses: actions/upload-artifact@v4
        with:
          name: wheel
          path: arrow/python/repaired_wheels/*.whl
      {{ macros.github_upload_releases("arrow/python/repaired_wheels/*.whl")|indent }}
      {{ macros.github_upload_wheel_scientific_python("arrow/python/repaired_wheels/*.whl")|indent }}
